services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: tankistpro512/voice-chat-user-service:latest
    container_name: voice-chat-user-service
    networks:
      - voice-chat-network
    restart: unless-stopped

networks:
  voice-chat-network:
    external: true
